#!/usr/bin/env bash
# Build & deploy pipeline for the Addon Manager Blueprint extension.
set -euo pipefail

# This script lives in tools/, so the checkout is its parent directory — the pipeline therefore works from any...
SCRIPT_DIR="$(cd -P "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SRC="${MI_SRC:-$(dirname "$SCRIPT_DIR")}"
PANEL="${PANEL_DIR:-/var/www/pterodactyl}"
IMPORTED_CSS="$PANEL/resources/scripts/blueprint/css/imported/modpackinstaller.css"
DEV_TREE="$PANEL/.blueprint/dev"
INSTALLED_APP="$PANEL/.blueprint/extensions/modpackinstaller/app"
INSTALLED_COMPONENTS="$PANEL/.blueprint/extensions/modpackinstaller/components"
INSTALLED_ROUTER="$PANEL/.blueprint/extensions/modpackinstaller/routers/client.php"

# ───────────────────────────── UI setup ─────────────────────────────
if [ -t 1 ]; then
  C_RESET=$'\e[0m';  C_DIM=$'\e[2m';    C_BOLD=$'\e[1m'
  C_GREEN=$'\e[38;5;114m'; C_CYAN=$'\e[38;5;81m'
  C_YELLOW=$'\e[38;5;179m'; C_RED=$'\e[38;5;203m'
  C_MAGENTA=$'\e[38;5;176m'; C_BLUE=$'\e[38;5;75m'
  TTY_UI=1
else
  C_RESET=""; C_DIM=""; C_BOLD=""; C_GREEN=""; C_CYAN=""
  C_YELLOW=""; C_RED=""; C_MAGENTA=""; C_BLUE=""
  TTY_UI=0
fi

BAR_WIDTH=24
SPIN_FRAMES=("⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏")

STEPS=("Root css" "Dev tree" "Extension app" "Extension router" "Extension config" "Config cache" "Cache flush" "Components" "Panel css" "Admin view" "Admin assets" "Ext conf" "Frontend build")
TOTAL=${#STEPS[@]}

WARNINGS=()          # unique captured warning lines
WARN_STEPS=()        # which step each warning came from
CHUNKS=0             # live: chunk lines seen in the webpack log
ASSETS=0             # live: asset lines seen in the webpack log
CUR_FILES=0          # live: files written to public/assets this build
EXPANDED=0
BAR_OPEN=0           # 1 = a live bar line is on screen (not newline-terminated)
RUN_PID=""
SAVED_STTY=""
START_MARKER="$(mktemp)"
touch "$START_MARKER"
LOG="$(mktemp -d)"

cleanup() {
  # Kill the whole step process tree — the subshell's children (rsync, php, yarn) would otherwise survive as...
  if [ -n "$RUN_PID" ]; then
    pkill -TERM -P "$RUN_PID" 2>/dev/null || true
    kill -TERM "$RUN_PID" 2>/dev/null || true
  fi
  if [ "$TTY_UI" = 1 ]; then
    if [ -n "$SAVED_STTY" ]; then
      stty "$SAVED_STTY" </dev/tty 2>/dev/null || true
    fi
    printf '\r\e[K\e[?25h'
  fi
  rm -rf "$LOG" "$START_MARKER"
}

# INT/TERM must hard-exit — a trap that only cleans up makes bash resume the loop, which looks like Ctrl+C...
on_interrupt() {
  trap - EXIT INT TERM
  cleanup
  exit 130
}
trap on_interrupt INT TERM
trap cleanup EXIT

step_cmd() {
  case "$1" in
    0) node "$SRC/tools/build-css.mjs" ;;
    1) sudo -n rsync -a --delete --exclude='.git' --exclude='*.sh' "$SRC/" "$DEV_TREE/" \
       && sudo -n chown -R www-data:www-data "$DEV_TREE" ;;
    2) sudo -n rsync -a --delete --exclude='.git' "$SRC/app/" "$INSTALLED_APP/" \
       && sudo -n chown -R www-data:www-data "$INSTALLED_APP" ;;
    3) sudo -n rsync -a "$SRC/client.php" "$INSTALLED_ROUTER" \
       && sudo -n chown www-data:www-data "$INSTALLED_ROUTER" ;;
    4) sudo -n rsync -a "$SRC/config/modpackinstaller.php" "$PANEL/config/modpackinstaller.php" \
       && sudo -n chown www-data:www-data "$PANEL/config/modpackinstaller.php" ;;
    5) cd "$PANEL" && sudo -n php artisan config:cache \
       && sudo -n chown -R www-data:www-data "$PANEL/bootstrap/cache" ;;
    6) # Flush ONLY this extension's cache keys (modpackinstaller:catalog:*)
       sudo -n php artisan tinker --execute '
    $store = Illuminate\Support\Facades\Cache::getStore();
    if (method_exists($store, "connection")) {
        $redis = $store->connection();
        $cursor = null;
        do {
            [$cursor, $keys] = $redis->scan(
                $cursor ?? 0,
                ["match" => "*modpackinstaller:catalog:*", "count" => 500],
            );
            if ($keys !== []) {
                $redis->del($keys);
            }
        } while ((int) $cursor !== 0);
    } else {
        Illuminate\Support\Facades\Cache::forget("modpackinstaller:catalog:providers");
    }
' || echo "cache flush skipped - store not reachable" ;;
    7) sudo -n rsync -a --delete --exclude='.git' "$SRC/components/" "$INSTALLED_COMPONENTS/" \
       && sudo -n chown -R www-data:www-data "$INSTALLED_COMPONENTS" ;;
    8) sudo -n rsync -a "$SRC/root.css" "$IMPORTED_CSS" \
       && sudo -n chown www-data:www-data "$IMPORTED_CSS" ;;
    9) # Admin view: the panel copy (resources/views/admin/extensions/
       # modpackinstaller/index.blade.php) is generated by Blueprint only at install time — it embeds extension...
       INSTALLED_VIEW="$PANEL/resources/views/admin/extensions/modpackinstaller/index.blade.php"
       LOCAL_VERSION="$(sed -n 's/^[[:space:]]*version:[[:space:]]*"\([^"]*\)".*/\1/p' "$SRC/conf.yml" | head -1)"
       # Icon: conf.yml points at a repo-relative image (e.g. assets/logo.png); Blueprint serves it from...
       LOCAL_ICON="$(sed -n 's/^[[:space:]]*icon:[[:space:]]*"\([^"]*\)".*/\1/p' "$SRC/conf.yml" | head -1)"
       LOCAL_ICON_EXT="${LOCAL_ICON##*.}"
       [ -n "$LOCAL_ICON" ] || LOCAL_ICON_EXT="jpg"
       LOCAL_ICON_URL="/assets/extensions/modpackinstaller/icon.$LOCAL_ICON_EXT"
       TMP_VIEW="$(mktemp)"
       {
         # The header is re-read from the installed copy, which Blueprint closes with the body's own opening `<?php` glued onto the
         # yield line. Trimming that line back to the yield keeps the rebuild idempotent — otherwise a second build opens PHP twice.
         sed -n '1,/extension\.description/p' "$INSTALLED_VIEW" \
           | sed -E -e 's~^(.*@yield\(.extension\.description.\)).*$~\1~' \
                    -e 's~\$EXTENSION_VERSION = ".*";~\$EXTENSION_VERSION = "'"${LOCAL_VERSION:-unknown}"'";~' \
                    -e 's~\$EXTENSION_ICON = ".*";~\$EXTENSION_ICON = "'"$LOCAL_ICON_URL"'";~'
         printf '\n'
         cat "$SRC/view.blade.php"
         printf '\n@endsection\n'
       } > "$TMP_VIEW"
       sudo -n cp "$TMP_VIEW" "$INSTALLED_VIEW" \
         && sudo -n chown www-data:www-data "$INSTALLED_VIEW"
       rm -f "$TMP_VIEW"
       # The admin controller is also only placed at Blueprint install time (from conf.yml admin.controller).
       sudo -n rsync -a "$SRC/app/AdminController.php" \
         "$PANEL/app/Http/Controllers/Admin/Extensions/modpackinstaller/modpackinstallerExtensionController.php" \
         && sudo -n chown www-data:www-data \
         "$PANEL/app/Http/Controllers/Admin/Extensions/modpackinstaller/modpackinstallerExtensionController.php"
       cd "$PANEL" && sudo -n php artisan view:clear ;;
    10)       # Admin assets (settings page styles + extension icon). Blueprint only
       # wires the css @import and copies the icon at install time — keep both in sync here (idempotent)....
       sudo -n rsync -a "$SRC/admin.style.css" \
         "$PANEL/.blueprint/extensions/modpackinstaller/assets/admin.style.css" \
         && sudo -n chown www-data:www-data \
         "$PANEL/.blueprint/extensions/modpackinstaller/assets/admin.style.css"
       ICON="$(sed -n 's/^[[:space:]]*icon:[[:space:]]*"\([^"]*\)".*/\1/p' "$SRC/conf.yml" | head -1)"
       ICON_EXT="${ICON##*.}"
       [ -n "$ICON" ] || ICON_EXT="jpg"
       if [ -n "$ICON" ] && [ -f "$SRC/$ICON" ]; then
         sudo -n rsync -a "$SRC/$ICON" \
           "$PANEL/.blueprint/extensions/modpackinstaller/assets/icon.$ICON_EXT" \
           && sudo -n chown www-data:www-data \
           "$PANEL/.blueprint/extensions/modpackinstaller/assets/icon.$ICON_EXT"
       fi
       BP_CSS="$PANEL/.blueprint/extensions/blueprint/assets/admin.extensions.css"
       IMPORT_LINE="@import url(/assets/extensions/modpackinstaller/admin.style.css);"
       if ! sudo -n grep -qF "$IMPORT_LINE" "$BP_CSS"; then
         printf '%s\n' "$IMPORT_LINE" | sudo -n tee -a "$BP_CSS" >/dev/null
       fi ;;
    11) # Installed conf.yml — drives the card version and the GitHub button
       # on the extension page header.
       sudo -n rsync -a "$SRC/conf.yml" \
         "$PANEL/.blueprint/extensions/modpackinstaller/private/.store/conf.yml" \
         && sudo -n chown www-data:www-data \
         "$PANEL/.blueprint/extensions/modpackinstaller/private/.store/conf.yml" ;;
    12) cd "$PANEL"
       BUILD_CHOWN="$PANEL/public/assets $PANEL/.build-cache.json"
       sudo -n chown -R "$(id -un):$(id -gn)" $BUILD_CHOWN
       trap 'sudo -n chown -R www-data:www-data $BUILD_CHOWN' RETURN
       NODE_OPTIONS="--openssl-legacy-provider --no-deprecation" yarn run build:production
       sudo -n chown -R www-data:www-data $BUILD_CHOWN
       trap - RETURN ;;
  esac
}

harvest_warnings() {
  local file="$1" idx="$2" live="${3:-0}"
  [ -s "$file" ] || return 0
  local line src="$file"
  # In live mode drop the trailing (possibly half-written) line so a truncated line never lands in the list as a...
  if [ "$live" = 1 ] && [ -n "$(tail -c1 "$file")" ]; then
    src=$(head -n -1 "$file")
  fi
  # webpack --progress writes \r-delimited (not \n) output with ANSI codes, and some notices (Browserslist,...
  while IFS= read -r line; do
    [ -n "$line" ] || continue
    if ! printf '%s\n' "${WARNINGS[@]:-}" | grep -qxF "$line"; then
      WARNINGS+=("$line")
      WARN_STEPS+=("${STEPS[$idx]}")
    fi
  done < <(tr '\r' '\n' < "$src" \
      | sed 's/\x1b\[[0-9;?]*[a-zA-Z]//g' \
      | grep -aiE 'warning|deprecat|browserslist|caniuse|baseline-browser' \
      | grep -aiEo '.{0,110}(warning|deprecat|browserslist|caniuse|baseline-browser).{0,110}' \
      | sed 's/^[^.|({[:space:]]*//; s/[^])}.!?]$//' \
      | sed 's/^[[:space:]]*//' \
      | sort -u || true)
}

poll_stats() {
  # Parse the still-growing build log: count what webpack has emitted so far, count real files landed in...
  local log="$1" idx="${2:-9}"
  CUR_FILES=$(find "$PANEL/public/assets" -type f -newer "$START_MARKER" 2>/dev/null | wc -l) || CUR_FILES=0
  if [ -s "$log" ]; then
    CHUNKS=$(grep -ac '^chunk ' "$log" 2>/dev/null) || CHUNKS=0
    ASSETS=$(grep -ac '^asset ' "$log" 2>/dev/null) || ASSETS=0
  fi
  harvest_warnings "$log" "$idx" 1
}

bar_glyphs() {
  # $1 = 0..1000 progress in tenths of a percent, $2 = spinner frame index
  local prog=$1 spin=$2 out="" ratio i
  ratio=$(( prog * BAR_WIDTH / 1000 ))
  for ((i = 0; i < BAR_WIDTH; i++)); do
    if (( i < ratio )); then
      out+="${C_GREEN}█"
    elif (( i == ratio && prog < 1000 )); then
      out+="${C_MAGENTA}${SPIN_FRAMES[$(( spin % ${#SPIN_FRAMES[@]} ))]}"
    else
      out+="${C_DIM}░"
    fi
  done
  printf '%s%s' "$out" "$C_RESET"
}

badge_seg() {
  # Compact badge rendered INSIDE the bar line.
  local wc=${#WARNINGS[@]}
  if (( wc > 0 )); then
    # plain string interpolation — no printf specifiers to mismatch
    printf '%s' " ${C_DIM}[w]${C_RESET} ${C_YELLOW}▲ ${wc}${C_RESET}"
  else
    printf '%s' " ${C_DIM}[w]${C_RESET} ${C_GREEN}✓${C_RESET}"
  fi
}

print_warnings_block() {
  # printed ONCE per expand — the bar simply continues on a new line below
  local wc=${#WARNINGS[@]} i
  if (( wc == 0 )); then
    printf '%s  (no warnings)%s\n' "$C_DIM" "$C_RESET"
    return
  fi
  local n=0
  for i in "${!WARNINGS[@]}"; do
    (( n >= 12 )) && { printf '%s  … +%d more%s\n' "$C_DIM" "$(( wc - 12 ))" "$C_RESET"; break; }
    printf '  %s▲%s %s %s\n' "$C_YELLOW" "$C_RESET" "${WARN_STEPS[$i]}:" "${WARNINGS[$i]}"
    n=$(( n + 1 ))
  done
}

draw() {
  # $1 = completed steps, $2 = current step idx (or -1 when finished), $3 = tick Everything on ONE line; single...
  local done=$1 cur=$2 tick=$3
  local prog=0 pct frac=0 elapsed

  if (( cur >= 0 )); then
    elapsed=$(( SECONDS - STEP_START ))
    # creep toward 95% of the current step so the bar always moves
    frac=$(( elapsed * 100 / (elapsed + 12) ))
    (( frac > 95 )) && frac=95
    prog=$(( (done * 1000 + frac * 10) / TOTAL ))
  else
    prog=1000
  fi
  (( prog > 1000 )) && prog=1000
  pct=$(( prog / 10 ))

  # compact live counters compact live counters (files + steps are shown in the end summary, so they don't need...
  local seg=""
  if (( CHUNKS > 0 )); then
    seg+=" ${C_CYAN}▦${C_RESET}${C_BOLD}${CHUNKS}${C_RESET}${C_DIM}c${C_RESET}"
  fi
  if (( ASSETS > 0 )); then
    seg+=" ${C_MAGENTA}▤${C_RESET}${C_BOLD}${ASSETS}${C_RESET}${C_DIM}a${C_RESET}"
  fi

  local frame=$(( tick % ${#SPIN_FRAMES[@]} ))
  local status
  if (( cur >= 0 )); then
    status="${C_CYAN}▶${C_RESET} ${STEPS[$cur]} ${C_DIM}· ${elapsed}s${C_RESET}"
  else
    status="${C_GREEN}✓${C_RESET} done"
  fi

  # ONE write — CR + erase-line + content (badge included).
  printf '\r\e[2K %s %s%3d%%%s %s  %s%s' \
    "$(bar_glyphs "$prog" "$frame")" "$C_BOLD" "$pct" "$C_RESET" \
    "$seg" "$status" "$(badge_seg)"
  BAR_OPEN=1
}

# ─────────────────────────── run pipeline ───────────────────────────
SECONDS=0
if [ "$TTY_UI" = 1 ]; then
  printf '\e[?25l'   # hide cursor while the bar is live
  # cbreak mode: read single keys without blocking, no echo
  SAVED_STTY=$(stty -g </dev/tty 2>/dev/null || true)
  stty -echo -icanon min 0 time 1 </dev/tty 2>/dev/null || true
fi

tick=0
for idx in "${!STEPS[@]}"; do
  STEP_START=$SECONDS
  step_log="$LOG/step_$idx.log"
  : > "$step_log"

  if [ "$TTY_UI" != 1 ]; then
    printf '%s▸%s step %d/%d · %s\n' "$C_BLUE" "$C_RESET" "$(( idx + 1 ))" "$TOTAL" "${STEPS[$idx]}"
  fi

  # background job gets its own stdin so it never fights the key reader
  step_cmd "$idx" > "$step_log" 2>&1 </dev/null &
  RUN_PID=$!

  while kill -0 "$RUN_PID" 2>/dev/null; do
    if [ "$TTY_UI" = 1 ]; then
      # poll keys fast, repaint at ~7fps — fewer writes = calmer terminals
      key=""
      IFS= read -r -t 0.07 -n 1 key </dev/tty || true
      if [ "$key" = "w" ] || [ "$key" = "W" ]; then
        EXPANDED=$(( 1 - EXPANDED ))
        if (( EXPANDED == 1 )); then
          draw "$idx" "$idx" "$tick"     # commit current frame
          printf '\n'                    # open the panel below the bar
          print_warnings_block
          BAR_OPEN=0
        fi
        tick=$(( tick + 1 ))
      fi
      if (( tick % 2 == 0 )); then
        # refresh counters + live warnings every few frames
        if (( tick % 6 == 0 )); then poll_stats "$step_log" "$idx"; fi
        draw "$idx" "$idx" "$tick"
      fi
      tick=$(( tick + 1 ))
    else
      sleep 0.5
    fi
  done

  status=0
  wait "$RUN_PID" || status=$?
  RUN_PID=""
  harvest_warnings "$step_log" "$idx"

  if [ "$status" -ne 0 ]; then
    if [ "$TTY_UI" = 1 ]; then
      printf '\n\e[?25h'   # commit bar line, restore cursor
    fi
    printf '%s✗ step failed: %s%s\n' "$C_RED" "${STEPS[$idx]}" "$C_RESET"
    printf '%s── last output ──────────────────────────%s\n' "$C_DIM" "$C_RESET"
    tail -n 20 "$step_log" || true
    exit "$status"
  fi

done

# ─────────────────────────── summary ──────────────────────────────── recount at the end — poll_stats only...
poll_stats "$LOG/step_12.log" 12 || true
BUILT_FILES=$CUR_FILES
DUR=$SECONDS
WARN_N=${#WARNINGS[@]}

if [ "$TTY_UI" = 1 ]; then
  if (( ! BAR_OPEN )); then
    draw "$TOTAL" -1 0     # single final frame if none is on screen
  fi
  printf '\n\e[?25h'   # commit the bar line exactly once, restore cursor
  # warnings sit between the finished bar and the completion line
  if [ "$WARN_N" -gt 0 ]; then
    printf '%s── warnings (%d) ─────────────────────────%s\n' "$C_YELLOW" "$WARN_N" "$C_RESET"
    for i in "${!WARNINGS[@]}"; do
      printf '  %s▲%s %s\n' "$C_YELLOW" "$C_RESET" "${WARNINGS[$i]}"
    done
  fi
  printf '%s ✓ sync complete%s\n' "$C_GREEN" "$C_RESET"
  printf '%s ✓ build complete%s  %s◷ %ds%s\n' \
    "$C_GREEN" "$C_RESET" \
    "$C_BLUE" "$DUR" "$C_RESET"
  printf '  %s▤ %d files%s  %s▦ %d chunks%s  %s▸ %d steps%s\n' \
    "$C_MAGENTA" "$BUILT_FILES" "$C_RESET" \
    "$C_CYAN" "$CHUNKS" "$C_RESET" \
    "$C_GREEN" "$TOTAL" "$C_RESET"
else
  printf '%s✓ sync complete%s\n' "$C_GREEN" "$C_RESET"
  printf '%s✓ build complete%s  %ds\n' "$C_GREEN" "$C_RESET" "$DUR"
  printf '  %d files · %d chunks · %d steps\n' "$BUILT_FILES" "$CHUNKS" "$TOTAL"
  if [ "$WARN_N" -gt 0 ]; then
    printf '%s── warnings (%d) ─────────────────────────%s\n' "$C_YELLOW" "$WARN_N" "$C_RESET"
    for i in "${!WARNINGS[@]}"; do
      printf '  %s▲%s %s\n' "$C_YELLOW" "$C_RESET" "${WARNINGS[$i]}"
    done
  fi
fi

exit 0
